apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webhook
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
      name: webhook
    spec:
      containers:
        - name: webhook
          image: az82/showcase-webhook
          imagePullPolicy: Never
          ports:
            - containerPort: 8443
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 1000m
              memory: 128Mi
          volumeMounts:
          - name: tls-secret
            mountPath: /.certs
            readOnly: true
        - name: opa-sidecar
          image: openpolicyagent/opa:0.10.1
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 1000m
              memory: 128Mi
          args:
          - "run"
          - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
          - "-s"
          - "-w"
          - "/policies"
          volumeMounts:
          - readOnly: true
            mountPath: /policies
            name: policies
      volumes:
      - name: tls-secret
        secret:
          secretName: webhook-tls
      - name: policies
        configMap:
          name: webhook-policies

---
kind: Service
apiVersion: v1
metadata:
  name: webhook
spec:
  selector:
    app: webhook
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: test-validating-webhook-configuration
webhooks:
  - name: test-validating-webhook.az82.de
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    failurePolicy: Fail
    clientConfig:
      service:
        name: webhook
        namespace: admissioncontrol
        path: "/validate"
      caBundle: REPLACE-ME
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled